pre-commit:
  commands:
    Freeze UV Dependencies:
      run: uv export --format requirements.txt --no-dev > requirements.txt && uv export --format requirements.txt --dev > requirements-dev.txt
      stage_fixed: true
      glob:
        - requirements-dev.txt
        - requirements.txt
        - uv.lock


post-merge:
  commands:
    Update UV Dependencies:
      run: uv sync
      glob:
        - uv.lock
    Update lefthook:
      run: uv run lefthook install
      glob:
        - .lefthook.yml