# Generated by Django 5.1 on 2026-01-30
# Migration for UserSettings model

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vignette_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Custom prompt for generating quiz/vignette questions. Leave blank to use default.",
                        null=True,
                    ),
                ),
                (
                    "spreadsheet_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Custom prompt for generating Excel study table. Leave blank to use default.",
                        null=True,
                    ),
                ),
                (
                    "spreadsheet_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom columns for Excel file. Each column should have 'name' and 'description' keys.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settings",
                "db_table": "user_settings",
            },
        ),
    ]
