# Generated by Django 6.0.1 on 2026-01-31 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this settings profile (e.g., 'Pathology', 'Cardiology')", max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Use this profile as the default for new handouts')),
                ('vignette_prompt', models.TextField(blank=True, help_text='Custom prompt for generating quiz/vignette questions. Leave blank to use default.', null=True)),
                ('spreadsheet_prompt', models.TextField(blank=True, help_text='Custom prompt for generating Excel study table. Leave blank to use default.', null=True)),
                ('spreadsheet_columns', models.JSONField(blank=True, default=list, help_text="Custom columns for Excel file. Each column should have 'name' and 'description' keys.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'setting profile',
                'verbose_name_plural': 'setting profiles',
                'db_table': 'setting_profiles',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
