# Generated by Django 6.0.1 on 2026-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingprofile',
            name='mindmap_prompt',
            field=models.TextField(blank=True, help_text='Custom prompt for generating mindmap diagram. Leave blank to use default.', null=True),
        ),
    ]
