# Generated by Django 6.0.1 on 2026-01-30 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskiq_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('current_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(max_length=50)),
                ('input_data', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('video_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture', to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lectures',
                'db_table': 'lectures',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('pdf_handout', 'PDF Handout'), ('excel_study_table', 'Excel Study Table'), ('pdf_vignette', 'PDF Vignette')], max_length=30)),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.lecture')),
            ],
            options={
                'verbose_name': 'artifact',
                'verbose_name_plural': 'artifacts',
                'db_table': 'artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
