# Generated by Django 5.1 on 2026-01-30
# Migration for Job per-job settings

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="enable_excel",
            field=models.BooleanField(
                default=True, help_text="Generate Excel study table for this job"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="enable_vignette",
            field=models.BooleanField(
                default=True, help_text="Generate vignette quiz questions for this job"
            ),
        ),
    ]
