# Generated by Django 6.0.1 on 2026-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_output_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
