# Generated by Django 6.0.1 on 2026-01-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_settingprofile'),
        ('core', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='setting_profile',
            field=models.ForeignKey(blank=True, help_text='Settings profile used for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.settingprofile'),
        ),
    ]
