# Generated by Django 6.0.1 on 2026-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_setting_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enable_mindmap',
            field=models.BooleanField(default=True, help_text='Generate mindmap diagram for this job'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('pdf_handout', 'PDF Handout'), ('excel_study_table', 'Excel Study Table'), ('pdf_vignette', 'PDF Vignette'), ('png_mindmap', 'PNG Mindmap')], max_length=30),
        ),
    ]
