# Generated by Django 6.0.1 on 2026-02-01 03:14

import django.db.models.deletion
from django.db import migrations, models


def migrate_lecture_data_to_jobs(apps, schema_editor):
    """Copy data from Lecture model to Job model and update Artifact FKs."""
    Lecture = apps.get_model("core", "Lecture")
    Job = apps.get_model("core", "Job")
    Artifact = apps.get_model("core", "Artifact")

    # Map lecture_id -> job_id for each lecture that has an associated job
    for lecture in Lecture.objects.select_related("job").all():
        if lecture.job:
            job = lecture.job
            # Copy lecture fields to job
            job.source_id = lecture.source_id
            job.title = lecture.title
            job.video_path = lecture.video_path
            job.save()

            # Update all artifacts for this lecture to point to the job
            Artifact.objects.filter(lecture_id=lecture.id).update(job_id=job.id)
        else:
            # Lecture without a job - artifacts will be orphaned
            # Delete these artifacts since there's no job to attach them to
            Artifact.objects.filter(lecture_id=lecture.id).delete()


def reverse_migration(apps, schema_editor):
    """Reverse migration is not fully supported - data may be lost."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_mindmap_support"),
    ]

    operations = [
        # 1. Add new fields to Job model
        migrations.AddField(
            model_name="job",
            name="source_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="video_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        # 2. Add job FK to Artifact (nullable for now)
        migrations.AddField(
            model_name="artifact",
            name="job",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="core.job",
            ),
        ),
        # 3. Run data migration to copy lecture data to jobs
        migrations.RunPython(migrate_lecture_data_to_jobs, reverse_migration),
        # 4. Remove the lecture FK from Artifact
        migrations.RemoveField(
            model_name="artifact",
            name="lecture",
        ),
        # 5. Make job FK non-nullable
        migrations.AlterField(
            model_name="artifact",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="core.job",
            ),
        ),
        # 6. Delete the Lecture model
        migrations.DeleteModel(
            name="Lecture",
        ),
    ]
