# Generated by Django 6.0.1 on 2026-02-02 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_artifact_lecture_artifact_job_job_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD based on model pricing', max_digits=10, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('cached', models.BooleanField(default=False, help_text='Whether result was from cache')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='core.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI request',
                'verbose_name_plural': 'AI requests',
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='ai_requests_created_fae1bf_idx'), models.Index(fields=['-created_at', 'job'], name='ai_requests_created_e00523_idx'), models.Index(fields=['function_name', '-created_at'], name='ai_requests_functio_52af8f_idx')],
            },
        ),
    ]
